name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Publish Image
      uses: matootie/github-docker@v3.1.0
      with:
        accessToken: ${{ github.token }}
